/* 사원 */
DROP TABLE EMPLOYEE 
	CASCADE CONSTRAINTS;

/* 부서 */
DROP TABLE DEPARTMENT 
	CASCADE CONSTRAINTS;

/* 사원 */
CREATE TABLE EMPLOYEE (
	EMPNO		NUMBER			NOT NULL, /* 사원번호 */
	EMPNAME		VARCHAR2(50)	NOT NULL, /* 사원명 */
	TITLE		VARCHAR2(50),	/* 직책 */
	MANAGER		NUMBER,			/* 직속상사 */
	SALARY		NUMBER,			/* 급여 */
	DNO			NUMBER			/* 부서 */
);

COMMENT ON TABLE EMPLOYEE IS '사원';

COMMENT ON COLUMN EMPLOYEE.EMPNO IS '사원번호';

COMMENT ON COLUMN EMPLOYEE.EMPNAME IS '사원명';

COMMENT ON COLUMN EMPLOYEE.TITLE IS '직책';

COMMENT ON COLUMN EMPLOYEE.MANAGER IS '직속상사';

COMMENT ON COLUMN EMPLOYEE.SALARY IS '급여';

COMMENT ON COLUMN EMPLOYEE.DNO IS '부서';

CREATE UNIQUE INDEX PK_EMPLOYEE
	ON EMPLOYEE (
		EMPNO ASC
	);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT PK_EMPLOYEE
		PRIMARY KEY (
			EMPNO
		);

/* 부서 */
CREATE TABLE DEPARTMENT (
	DEPTNO 		NUMBER			NOT NULL, /* 부서번호 */
	DEPTNAME	VARCHAR2(50)	NOT NULL, /* 부서명 */
	FLOOR		NUMBER			/* 위치 */
);

COMMENT ON TABLE DEPARTMENT IS '부서';

COMMENT ON COLUMN DEPARTMENT.DEPTNO IS '부서번호';

COMMENT ON COLUMN DEPARTMENT.DEPTNAME IS '부서명';

COMMENT ON COLUMN DEPARTMENT.FLOOR IS '위치';

CREATE UNIQUE INDEX PK_DEPARTMENT
	ON DEPARTMENT (
		DEPTNO ASC
	);

ALTER TABLE DEPARTMENT
	ADD
		CONSTRAINT PK_DEPARTMENT
		PRIMARY KEY (
			DEPTNO
		);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT FK_EMPLOYEE_TO_EMPLOYEE
		FOREIGN KEY (
			MANAGER
		)
		REFERENCES EMPLOYEE (
			EMPNO
		);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT FK_DEPARTMENT_TO_EMPLOYEE
		FOREIGN KEY (
			DNO
		)
		REFERENCES DEPARTMENT (
			DEPTNO
		);