SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO FROM EMPLOYEE;

SELECT *
  FROM EMPLOYEE
 WHERE EMPNO = 4377;

INSERT INTO EMPLOYEE(EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO)
VALUES (1004, '이유영', '과장', 4377, 4100000, 1);

UPDATE EMPLOYEE
   SET EMPNAME = '영유이', TITLE = '대리', MANAGER = 1003, SALARY = 3100000, DNO = 2
 WHERE EMPNO = 1004;

DELETE
  FROM EMPLOYEE
 WHERE EMPNO = 1004;

SELECT DEPTNO, DEPTNAME, FLOOR FROM DEPARTMENT;
  
SELECT *
  FROM DEPARTMENT
 WHERE DEPTNO = 1;

INSERT INTO DEPARTMENT(DEPTNO, DEPTNAME, FLOOR)
VALUES (5, '인사', 6);

UPDATE DEPARTMENT
   SET DEPTNAME = '시설', FLOOR = 1
 WHERE DEPTNO = 5;

DELETE FROM DEPARTMENT
 WHERE DEPTNO = 5;