SELECT *
  FROM DEPARTMENT;
  
SELECT EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO FROM EMPLOYEE;

SELECT *
  FROM EMPLOYEE
 WHERE EMPNO = 4377;

INSERT INTO EMPLOYEE(EMPNO, EMPNAME, TITLE, MANAGER, SALARY, DNO)
VALUES (1004, '이유영', '과장', 4377, 4100000, 1);

DELETE
  FROM EMPLOYEE
 WHERE EMPNO = 1004;

